### ISSUE TITLE
Ошибка при работе с создаваемыми объектами!

### ISSUE THREAD

**Issue by mrals2018** [moexalgo/moexalgo#2]
День добрый!
Установил данный пакет, решил написать простенькую программу и в итоге постоянно получаю одну и ту же ошибку

`AttributeError: 'generator' object has no attribute 'head'`

Код следующий (два варианта)
```
sber = Ticker('SBER')
sber.candles(date='2023-12-01', till_date='2023-12-31', period='D').head()
```

Или
```
sber = Ticker('SBER')
sber.orderstats(date='2023-10-10').head()
```

Не могу понять в чем проблема у меня?

**Comment by KaigorodovTuskul** [comment]
> День добрый! Установил данный пакет, решил написать простенькую программу и в итоге постоянно получаю одну и ту же ошибку
> 
> `AttributeError: 'generator' object has no attribute 'head'`
> 
> Код следующий (два варианта)
> 
> ```
> sber = Ticker('SBER')
> sber.candles(date='2023-12-01', till_date='2023-12-31', period='D').head()
> ```
> 
> Или
> 
> ```
> sber = Ticker('SBER')
> sber.orderstats(date='2023-10-10').head()
> ```
> 
> Не могу понять в чем проблема у меня?

В jupyter, colab? Или через IDE? Если первое, то нужно больше вводных, может криво импортируете? Сначала !pip install moexalgo затем from moexalgo import Ticker. Если же через IDE, тогда надо pandas импортировать затем обернуть в датафрейм, на подобии df = pd.DataFrame(sber.candles(date='2023-12-01', till_date='2023-12-31', period='D')), затем print(df.head())

**Comment by moexalgo** [comment]
Библиотеку обновили, такой проблемы больше нет.

pip install --upgrade moexalgo

Это было связано с тем, что если был импорт pandas в коде -> данные приходили как dataframe
В остальных случаях как iterator

В новой версии, данные приходят как dataframe
